# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp
#   labels:
#     app: webapp
#     release: '0'
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp0-5
#   labels:
#     app: webapp
#     release: '0.5'
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  containers:
  - name: activemq
    image: richardchesterwood/k8s-fleetman-queue:release1
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8161
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: mysql
#   namespace: default
#   labels:
#     app: mysql
# spec:
#   containers:
#   - name: mysql
#     image: mysql:5
#     resources:
#       limits:
#         cpu: 200m
#         memory: 500Mi
#       requests:
#         cpu: 100m
#         memory: 200Mi
#     env:
#     - name: MYSQL_ROOT_PASSWORD
#       value: password
#     - name: MYSQL_DATABASE
#       value: fleetman
#     ports:
#     - containerPort:  3306
#       name:  tcp
#   restartPolicy: Always