apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  selector:
    app: queue
  ports:
  - name: http
    port: 8161
    targetPort: 8161
    nodePort: 30010
  - name: endpoint
    port: 61616
    targetPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: tcp
    port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  type: ClusterIP
  selector:
    app: position-tracker
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-angular
spec:
  type: NodePort
  selector:
    app: webapp-angular
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080