apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: default
  labels:
    app: mongo-pvc
spec:
  storageClassName: localstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: default
  labels:
    app: local-storage
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/yannis/Storage
    type: DirectoryOrCreate
  capacity:
    storage: 10Gi